import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Main 페이지 입니다</h1>
        </div>

        <div>
          <Image className={styles.logo} src="/next.svg" alt="Next.js Logo" width={150} height={37} priority />
        </div>

        <div className={styles.grid}>
          <Link href={"/about"}>about 페이지로 이동</Link>
        </div>
      </main>
    </>
  );
}
